### PR TITLE
More Translateables

### PR DESCRIPTION
**Pull request by AntonCrusader**
You can translate almost all text ingame now :D

Everything tested and works fine.

### CODE REVIEW

**Comment by JetBoom** [comment]
Doing SWEP.PrintName = translate.get something won't work.
That line is only executed at game start. If you change languages mid-game then the names won't update.

**Comment by AntonCrusader** [comment]
Oh sorry. I'll fix this in few moments

**Comment by AntonCrusader** [comment]
Just fixed ;)

**Comment by AntonCrusader** [comment]
Okay, hopefully fixed

**Comment by AntonCrusader** [comment]
I hope everyithing is ready

**Comment by AntonCrusader** [comment]
Accept pull request

**Comment by AntonCrusader** [comment]
ayy wtf

**Comment by AntonCrusader** [comment]
whats wrong?

**Comment by JetBoom** [comment]
Adding "".. doesn't fix what I said and I don't think you understand what I even said in the first place.

**Pull request closed without merging**
